language: cpp
compiler: gcc
os: linux
dist: xenial
before_script: autoreconf -i
git:
  depth: 3
addons:
  apt:
    packages:
      - bison
      - flex

matrix:
  include:
    - script: ./configure && make
    - script: ./configure --host=x84_64-w64-mingw32 && make
      addons:
        apt:
          packages:
            - mingw-w64
