language: cpp
compiler: gcc
os: linux
dist: xenial
before_script: autoreconf -i
git:
  depth: 3
addons:
  apt:
    packages:
      - bison
      - flex

matrix:
  include:
    - os: linux
      compiler: gcc
      script: ./configure && make
      env:
        - MATRIX_CC=gcc
        - MATRIX_CXX=g++
    - os: linux
      compiler: x86_64-w64-mingw32-g++
      env:
        - MATRIX_CC=x86_64-w64-mingw32-gcc
        - MATRIX_CXX=x86_64-w64-mingw32-g++
      script: ./configure --host=x84_64-w64-mingw32 && make
      addons:
        apt:
          packages:
            - mingw-w64

before_install:
  - eval "CC=${MATRIX_CC} && CXX=${MATRIX_CXX}"
